# Generated by Django 4.0.10 on 2024-03-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_by',
            new_name='author',
        ),
    ]
